// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNgPTzTaI9XLkcdUMAHz1qh6xUbGNbwg',
    appId: '1:414840726467:web:be1e9aa2c6b1a243c45376',
    messagingSenderId: '414840726467',
    projectId: 'dimaano-clinic-system',
    authDomain: 'dimaano-clinic-system.firebaseapp.com',
    storageBucket: 'dimaano-clinic-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8-lSViI9SGiLbPYBnC86XcIthIqbxWsY',
    appId: '1:414840726467:android:9e741919541f8e5ac45376',
    messagingSenderId: '414840726467',
    projectId: 'dimaano-clinic-system',
    storageBucket: 'dimaano-clinic-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1HalxRXuf_xM1tdceDPOwkKv_SyNitg',
    appId: '1:414840726467:ios:6babed57c0ccde00c45376',
    messagingSenderId: '414840726467',
    projectId: 'dimaano-clinic-system',
    storageBucket: 'dimaano-clinic-system.firebasestorage.app',
    iosClientId: '414840726467-sfs613n7gdvb73eocfnee6lt0igj1v16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV1HalxRXuf_xM1tdceDPOwkKv_SyNitg',
    appId: '1:414840726467:ios:6babed57c0ccde00c45376',
    messagingSenderId: '414840726467',
    projectId: 'dimaano-clinic-system',
    storageBucket: 'dimaano-clinic-system.firebasestorage.app',
    iosClientId: '414840726467-sfs613n7gdvb73eocfnee6lt0igj1v16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsNgPTzTaI9XLkcdUMAHz1qh6xUbGNbwg',
    appId: '1:414840726467:web:0d480a580b156715c45376',
    messagingSenderId: '414840726467',
    projectId: 'dimaano-clinic-system',
    authDomain: 'dimaano-clinic-system.firebaseapp.com',
    storageBucket: 'dimaano-clinic-system.firebasestorage.app',
  );
}
